language: python
python:
  - "3.8"
  - "3.8-dev"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run -m pytest --ignore scripts/
after_success: 
  - bash <(curl -s https://codecov.io/bash)
